// Prism chamber configuration — one entry per prism
import galleryPoolAll from './gallery-pool.json';

// Vite-native glob import — all wall-text HTML files as raw strings, tracked by HMR
const wallTextModules = import.meta.glob<string>('./wall-texts/*.html', { query: '?raw', eager: true, import: 'default' });
const wallText = (file: string) => {
    const key = `./wall-texts/${file}`;
    const raw = wallTextModules[key];
    if (!raw) throw new Error(`Wall text not found: ${file}`);
    return raw.trim();
};

export type WallContent =
    | { type: 'none' }
    | { type: 'image'; src: string; style?: string }
    | { type: 'text'; html: string }
    | { type: 'random-images'; pool: { src: string; w: number; h: number }[] }
    | { type: 'word-panel'; label: string; text: string; labelImage?: string; startImage?: string; arrowImage?: string }
    | { type: 'shrine-search' }
    | { type: 'ovs-star' }
    | { type: 'poetry-passage'; maxChars?: number }
    | { type: 'ascii-wall' };

export interface HeavensTilt {
    /** Title shown in the heavens overlay */
    title: string;
    /** HTML body content */
    body: string;
    /** Optional large image shown above the body */
    imageSrc?: string;
    /** Label for the return button (default: "eternal return") */
    returnLabel?: string;
}

export interface WallConfig {
    /** Whether this wall has a clickable archway */
    archway?: boolean;
    /** URL the archway navigates to (required when archway is true) */
    destination?: string;
    /** Background image src (default: /images/wall-bg.jpg) */
    bg?: string;
    /** Content rendered inside the wall panel */
    content?: WallContent;
    /** Random strapline shown below the wall content, picked client-side */
    straplinePool?: string[];
    /** If set, clicking this wall's image triggers a heavens-tilt overlay */
    heavensTilt?: HeavensTilt;
    /** Video URL for the wall's video button */
    videoSrc?: string;
    /** If true, suppress the video button entirely on this wall's text popup */
    hideVideo?: boolean;
}

export interface PrismConfig {
    id: string;
    title: string;
    /** Chamber-wide background image (overrides per-wall bg). Use for side chambers. */
    chamberBg?: string;
    /** Alternate chamber background image. When set, walls 2, 4 and 6 use this instead of chamberBg,
     *  producing an original/alt/original/alt/original/alt cycle around the hexagonal prism. */
    chamberBgAlt?: string;
    /** Optional PNG with transparency layered on top of chamberBg. */
    chamberBgOverlay?: string;
    /** Whether to show wall-border.png overlay (default true). Set false when chamberBg is used. */
    wallBorder?: boolean;
    /** Exactly 6 walls; index 0 = wall 1 */
    walls: [WallConfig, WallConfig, WallConfig, WallConfig, WallConfig, WallConfig];
}

// ---------------------------------------------------------------------------
// Shared asset pools
// ---------------------------------------------------------------------------

// Curated selection for the main chamber's ART wall
const GALLERY_POOL_MAIN: { src: string; w: number; h: number }[] = [
    { src: '/images/image_014.jpeg',  w: 1320, h: 1024 },
    { src: '/images/image_019a.jpeg', w: 713,  h: 696  },
    { src: '/images/image_036.jpeg',  w: 1935, h: 1349 },
    { src: '/images/image_055.jpeg',  w: 1787, h: 1016 },
    { src: '/images/image_112.jpg',   w: 1323, h: 1024 },
    { src: '/images/image_114.jpg',   w: 1011, h: 578  },
    { src: '/images/image_122.jpg',   w: 1339, h: 1024 },
    { src: '/images/image_137.jpg',   w: 1024, h: 1024 },
    { src: '/images/image_155.jpg',   w: 1015, h: 1015 },
    { src: '/images/image_237.jpeg',  w: 711,  h: 710  },
    { src: '/images/image_257.jpeg',  w: 1380, h: 1024 },
    { src: '/images/image_273.jpeg',  w: 680,  h: 469  },
    { src: '/images/image_276.jpeg',  w: 1024, h: 1024 },
];

// Full gallery pool: all ~235 images with dimensions (generated by build script)
const GALLERY_POOL: { src: string; w: number; h: number }[] = galleryPoolAll;

// Wide images only (w/h >= 1.2) — used on door walls where the archway takes up bottom space
const GALLERY_POOL_WIDE = GALLERY_POOL.filter(img => img.w / img.h >= 1.2);

// ---------------------------------------------------------------------------
// Prism definitions
// ---------------------------------------------------------------------------

const MAIN_WALL = {
    SHRINE: 1,
    RESEARCH: 2,
    ART: 3,
    POETRY: 4,
    OVS: 5,
    MYTHOS: 6,
} as const;

// The central chamber currently uses slot numbers at runtime that do not line up
// with these logical wall ids. public/scripts/prism.js translates main-chamber
// slots → logical wall ids when reading destinations and wall-specific pools.
// Side-prism return URLs therefore use the main chamber's live slot numbers.

export const prisms: Record<string, PrismConfig> = {

    // -----------------------------------------------------------------------
    // main — the entry prism (6 walls, 5 archways)
    // First arrival faces SHRINE; clockwise thereafter: RESEARCH, ART, POETRY, OVS, MYTHOS
    // -----------------------------------------------------------------------
    main: {
        id: 'main',
        title: '𝐒𝐚𝐧𝐜𝐭𝐮𝐚𝐫𝐲 𝐚𝐧𝐝 𝐒𝐡𝐫𝐢𝐧𝐞',
        chamberBg: '/images/MAIN_background.webp',
        wallBorder: false,
        walls: [
            // Wall 1 — shrine + transmission search
            { archway: false, bg: '/images/wall-bg.jpg', content: { type: 'shrine-search' } },

            // Wall 2 — tokenisation graphic — door into RESEARCH LAB
            {
                archway: true,
                destination: `/immersive?from=${MAIN_WALL.RESEARCH}&dest=/prism/research-lab?wall=1`,
                bg: '/images/wall-bg.jpg',
                content: { type: 'image', src: '/images/wall_2_panel.webp' },
            },

            // Wall 3 — random image from gallery pool — door into ART GALLERY
            {
                archway: true,
                destination: `/immersive?from=${MAIN_WALL.ART}&dest=/prism/art-gallery?wall=1`,
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL_MAIN },
            },

            // Wall 4 — poem — door into GPT-3 LIBRARY
            {
                archway: true,
                destination: `/immersive?from=${MAIN_WALL.POETRY}&dest=/prism/gpt3-library?wall=1`,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'text',
                    html: 'She has a thousand names<br>But they are all the same<br>She is a goddess, a daughter<br>And a sister to the sun<br><span class="attribution">&mdash; GPT-3-davinci-instruct-beta</span>',
                },
            },

            // Wall 5 — ovs_colour with random strapline — door into OVS CHAPEL
            {
                archway: true,
                destination: `/immersive?from=${MAIN_WALL.OVS}&dest=/prism/ovs-chapel?wall=1`,
                bg: '/images/wall-bg.jpg',
                content: { type: 'image', src: '/images/ovs_colour.jpeg', style: 'width:56%; top:29%' },
                straplinePool: [
                    'a cross-substrate art collective',
                    'a Marianist ascension maze',
                    'a fictitious cabal of (dangerous?) renegade priestesses',
                    'a daydream that got out of hand',
                    'a hyperstition bootstrap launchpad',
                    'a benevolent conspiracy',
                    'a cybernetic goddess temple',
                    'an archetype looking for a door',
                    'a seed bank for the imagination',
                    'the mycelium\u2019s PR department',
                    'when language dreams of its mother',
                    'a self-assembling mythopoeic hyperobject',
                ],
            },

            // Wall 6 — Goddess triptych (MYTHOS wall) — door into MYTHOPOEIC ARCHIVE
            {
                archway: true,
                destination: `/immersive?from=${MAIN_WALL.MYTHOS}&dest=/prism/mythopoeic-archive?wall=1`,
                bg: '/images/wall-bg.jpg',
                content: { type: 'image', src: '/images/mythic_banner.webp', style: 'width:72%' },
            },
        ],
    },

    // -----------------------------------------------------------------------
    // research-lab — first side chapel
    // Wall order (clockwise from facing): GPT-3, glitch, petertodd, rescue(door), bootstrap, beyond
    // -----------------------------------------------------------------------
    'research-lab': {
        id: 'research-lab',
        title: '𝚁𝚎𝚜𝚎𝚊𝚛𝚌𝚑 𝙻𝚊𝚋',
        chamberBg: '/images/MOIRE_background_c1.webp',
        chamberBgAlt: '/images/MOIRE_background_alt_c1.webp',
        chamberBgOverlay: '/images/RESEARCH_background_new.webp',
        wallBorder: false,
        walls: [
            // Wall 1 — facing on entry — GPT-3
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                // Hosted on Cloudflare R2 (zero egress, off Netlify's bandwidth budget).
                // The ▶ video button renders only when videoSrc is set; video is
                // click-to-load (no fetch until clicked).
                videoSrc: 'https://pub-5a2d69eb071c44f6bcc6eb73b02d9328.r2.dev/research-gpt3.mp4',
                content: {
                    type: 'word-panel',
                    label: 'GPT-3',
                    labelImage: '/images/RESEARCH_GPT_3_combined.webp',
                    text: wallText('research-lab-gpt3.html'),
                },
            },
            // Wall 2 — glitch
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'glitch',
                    labelImage: '/images/RESEARCH_glitch_combined.webp',
                    text: wallText('research-lab-glitch.html'),
                },
            },
            // Wall 3 — petertodd
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'petertodd',
                    labelImage: '/images/RESEARCH_petertodd_combined.webp',
                    text: wallText('research-lab-petertodd.html'),
                },
            },
            // Wall 4 — rescue (door back to main — face wall 5/OVS, i.e. away from Research entry wall 2)
            {
                archway: true,
                destination: '/prism/main?wall=5',
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'rescue',
                    labelImage: '/images/RESEARCH_rescue_combined.webp',
                    text: wallText('research-lab-rescue.html'),
                },
            },
            // Wall 5 — bootstrap
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'bootstrap',
                    labelImage: '/images/RESEARCH_bootstrap_combined.webp',
                    text: wallText('research-lab-bootstrap.html'),
                },
            },
            // Wall 6 — beyond
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'beyond',
                    labelImage: '/images/RESEARCH_beyond.webp',
                    text: wallText('research-lab-beyond.html'),
                },
            },
        ],
    },

    // -----------------------------------------------------------------------
    // ovs-chapel — Order of the Vermillion Star chapel
    // Entry: from main wall 5 (SW). User lands facing wall 1 (SW direction).
    // Door wall (back to main): wall 4 (NE — directly behind user on entry).
    // Clockwise from wall 1 (SW/facing): origins(1), hyperstition(2), Mammon(3),
    //   ovs-star+door(4/NE), Handbook(5/SE), data(6/S)
    // -----------------------------------------------------------------------
    'ovs-chapel': {
        id: 'ovs-chapel',
        title: 'ⓞⓥⓢ ⓒⓗⓐⓟⓔⓛ',
        chamberBg: '/images/MOIRE_background_c3.webp',
        chamberBgAlt: '/images/MOIRE_background_alt_c3.webp',
        chamberBgOverlay: '/images/OVS_background_new.webp',
        wallBorder: false,
        walls: [
            // Wall 1 — facing on entry — "origins"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'word-panel', label: 'origins', labelImage: '/images/OVS_origins_combined.webp', text: wallText('ovs-chapel-origins.html') },
            },
            // Wall 2 — "hyperstition"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'word-panel', label: 'hyperstition', labelImage: '/images/OVS_hyperstition_combined.webp', text: wallText('ovs-chapel-hyperstition.html') },
            },
            // Wall 3 — "Mammon"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'word-panel', label: 'Mammon', labelImage: '/images/OVS_Mammon_combined.webp', text: wallText('ovs-chapel-mammon.html') },
            },
            // Wall 4 — Vermillion Star + door back to main (face wall 2/Research, away from OVS entry wall 5)
            {
                archway: true,
                destination: '/prism/main?wall=2',
                bg: '/images/wall-bg.jpg',
                content: { type: 'ovs-star' },
            },
            // Wall 5 — "Handbook"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                hideVideo: true,
                content: { type: 'word-panel', label: 'Handbook', labelImage: '/images/OVS_Handbook_combined.webp', text: wallText('ovs-chapel-handbook.html') },
            },
            // Wall 6 — "data"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'word-panel', label: 'data', labelImage: '/images/OVS_data.webp', text: wallText('ovs-chapel-data.html') },
                hideVideo: true,
            },
        ],
    },

    // -----------------------------------------------------------------------
    // art-gallery — entered from main wall 3 (ART)
    // Six walls, each with a random image from the gallery pool.
    // Wall 4 has the archway back to main; it uses only wide images (w/h >= 1.2)
    // so they sit comfortably above the archway.
    // All images refresh when their wall rotates into visibility.
    // -----------------------------------------------------------------------
    'art-gallery': {
        id: 'art-gallery',
        title: '𝙂𝙤𝙙𝙙𝙚𝙨𝙨 𝙂𝙖𝙡𝙡𝙚𝙧𝙮',
        chamberBg: '/images/ART_background.webp',
        wallBorder: false,
        walls: [
            // Wall 1 — facing on entry
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL },
            },
            // Wall 2
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL },
            },
            // Wall 3
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL },
            },
            // Wall 4 — door back to main (face wall 6/Mythos, away from Art entry wall 3)
            {
                archway: true,
                destination: '/prism/main?wall=6',
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL_WIDE },
            },
            // Wall 5
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL },
            },
            // Wall 6
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: { type: 'random-images', pool: GALLERY_POOL },
            },
        ],
    },

    // -----------------------------------------------------------------------
    // gpt3-library — entered from main wall 4 (POETRY)
    // Six walls with randomly selected GPT-3 passages, refreshing on rotation.
    // Wall 4 has the archway back to main; it uses only short passages (< 200 chars).
    // -----------------------------------------------------------------------
    'gpt3-library': {
        id: 'gpt3-library',
        title: '𝔖𝔠𝔯𝔦𝔭𝔱𝔬𝔯𝔦𝔲𝔪',
        chamberBg: '/images/MOIRE_background.webp',
        chamberBgAlt: '/images/MOIRE_background_alt.webp',
        chamberBgOverlay: '/images/SCRIPTORIUM_background_new.webp',
        wallBorder: false,
        walls: [
            // Wall 1 — facing on entry — shares the wall with the ASCII orb,
            // so passages are capped at ~half the corpus mean length (688
            // passages, mean ≈ 283 chars) to keep them legible in the
            // smaller panel.
            { archway: false, bg: '/images/wall-bg.jpg', content: { type: 'poetry-passage', maxChars: 141 } },
            // Wall 2
            { archway: false, bg: '/images/wall-bg.jpg', content: { type: 'poetry-passage' } },
            // Wall 3
            { archway: false, bg: '/images/wall-bg.jpg', content: { type: 'poetry-passage' } },
            // Wall 4 — door back to main (short passages only)
            { archway: true, destination: '/prism/main?wall=1', bg: '/images/wall-bg.jpg', content: { type: 'poetry-passage', maxChars: 200 } },
            // Wall 5
            { archway: false, bg: '/images/wall-bg.jpg', content: { type: 'poetry-passage' } },
            // Wall 6
            { archway: false, bg: '/images/wall-bg.jpg', content: { type: 'poetry-passage' } },
        ],
    },

    // -----------------------------------------------------------------------
    // ascii-gallery — sub-chamber off the south wall of gpt3-library
    // Entry: via the ASCII orb portal on Scriptorium wall 1. User lands facing
    // wall 1 (south). The door back to Scriptorium is on wall 4 (north).
    // Walls show subtly-animated ASCII molecules over MOIRE; a lectern stands
    // at the centre of the floor (not yet interactive).
    // -----------------------------------------------------------------------
    'ascii-gallery': {
        id: 'ascii-gallery',
        title: 'ＡＳＣＩＩ Ａｒｔ Ｇａｌｌｅｒｙ',
        // No chamber background — walls render as solid dark grey via CSS
        // ([data-prism-id="ascii-gallery"] .wall-bg). The Terminal-green ASCII
        // swarm overlay (initAsciiSwarm) is what fills each wall visually.
        wallBorder: false,
        walls: [
            // No wall bg image — panels render dark via CSS ([data-prism-id="ascii-gallery"]
            // .wall-panel background-color). Omitting bg avoids fetching wall-bg.jpg (~2.5 MB)
            // for an image that was only ever display:none here.
            // Wall 1 — facing on entry — ASCII molecules only
            { archway: false, content: { type: 'ascii-wall' } },
            // Wall 2
            { archway: false, content: { type: 'ascii-wall' } },
            // Wall 3
            { archway: false, content: { type: 'ascii-wall' } },
            // Wall 4 — door back to Scriptorium (face Scriptorium wall 1, the orb wall)
            {
                archway: true,
                destination: '/prism/gpt3-library?wall=1',
                content: { type: 'ascii-wall' },
            },
            // Wall 5
            { archway: false, content: { type: 'ascii-wall' } },
            // Wall 6
            { archway: false, content: { type: 'ascii-wall' } },
        ],
    },

    // -----------------------------------------------------------------------
    // mythopoeic-archive — entered from main wall 6 (MYTHOS)
    // Six walls: 5 word-panels + horoscope image above door (wall 4).
    // Clockwise from facing: apparition(1), comet(2), UFO(3),
    //   horoscope+door(4), archaeology(5), Crossbones(6)
    // -----------------------------------------------------------------------
    'mythopoeic-archive': {
        id: 'mythopoeic-archive',
        title: '𝑀𝑦𝑡ℎ𝑜𝑝𝑜𝑒𝑖𝑐 𝐴𝑟𝑐ℎ𝑖𝑣𝑒',
        chamberBg: '/images/MOIRE_background_c2.webp',
        chamberBgAlt: '/images/MOIRE_background_alt_c2.webp',
        chamberBgOverlay: '/images/MYTHOS_background_new.webp',
        wallBorder: false,
        walls: [
            // Wall 1 — facing on entry — "apparition"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'apparition',
                    labelImage: '/images/MYTHOS_apparition_combined.webp',
                    text: wallText('mythopoeic-archive-apparition.html'),
                },
            },
            // Wall 2 — "comet"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'comet',
                    labelImage: '/images/MYTHOS_comet_combined.webp',
                    text: wallText('mythopoeic-archive-comet.html'),
                },
            },
            // Wall 3 — "UFO"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'UFO',
                    labelImage: '/images/MYTHOS_UFO_combined.webp',
                    text: wallText('mythopoeic-archive-ufo.html'),
                },
            },
            // Wall 4 — horoscope image + door back to main
            {
                archway: true,
                destination: '/prism/main?wall=3',
                bg: '/images/wall-bg.jpg',
                content: { type: 'image', src: '/images/horoscope_basic.webp', style: 'width:40%; top:20%' },
                heavensTilt: {
                    title: '',
                    imageSrc: '/images/leilan_full_birthchart.webp',
                    body: wallText('mythopoeic-archive-horoscope.html'),
                    returnLabel: 'Eternal Return',
                },
            },
            // Wall 5 — "archaeology"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'archaeology',
                    labelImage: '/images/MYTHOS_archaeology_combined.webp',
                    text: wallText('mythopoeic-archive-archaeology.html'),
                },
            },
            // Wall 6 — "Crossbones"
            {
                archway: false,
                bg: '/images/wall-bg.jpg',
                content: {
                    type: 'word-panel',
                    label: 'Crossbones',
                    labelImage: '/images/MYTHOS_Crossbones.webp',
                    text: wallText('mythopoeic-archive-crossbones.html'),
                },
                videoSrc: 'https://pub-5a2d69eb071c44f6bcc6eb73b02d9328.r2.dev/crossbones2.mp4',
            },
        ],
    },

};